class RenameCaptainInstallationConfigsToTekomi < ActiveRecord::Migration[7.1]
  RENAMES = {
    'CAPTAIN_OPEN_AI_API_KEY' => 'TEKOMI_OPEN_AI_API_KEY',
    'CAPTAIN_OPEN_AI_MODEL' => 'TEKOMI_OPEN_AI_MODEL',
    'CAPTAIN_OPEN_AI_ENDPOINT' => 'TEKOMI_OPEN_AI_ENDPOINT',
    'CAPTAIN_EMBEDDING_MODEL' => 'TEKOMI_EMBEDDING_MODEL',
    'CAPTAIN_FIRECRAWL_API_KEY' => 'TEKOMI_FIRECRAWL_API_KEY',
    'CAPTAIN_CLOUD_PLAN_LIMITS' => 'TEKOMI_CLOUD_PLAN_LIMITS',
    'CAPTAIN_TOPUP_OPTIONS' => 'TEKOMI_TOPUP_OPTIONS',
    'CAPTAIN_DOCUMENT_AUTO_SYNC_INTERVALS' => 'TEKOMI_DOCUMENT_AUTO_SYNC_INTERVALS',
    'CAPTAIN_DOCUMENT_AUTO_SYNC_PER_ACCOUNT_BATCH_LIMIT' => 'TEKOMI_DOCUMENT_AUTO_SYNC_PER_ACCOUNT_BATCH_LIMIT',
    'CAPTAIN_DOCUMENT_AUTO_SYNC_GLOBAL_BATCH_LIMIT' => 'TEKOMI_DOCUMENT_AUTO_SYNC_GLOBAL_BATCH_LIMIT'
  }.freeze

  def up
    RENAMES.each { |old, new| execute "UPDATE installation_configs SET name = '#{new}' WHERE name = '#{old}'" }
  end

  def down
    RENAMES.each { |old, new| execute "UPDATE installation_configs SET name = '#{old}' WHERE name = '#{new}'" }
  end
end
